### ISSUE TITLE
support Minecraft 1.17.33

### ISSUE THREAD

**Issue by MyNameInc** [mhsjlw/pocket-minecraft-protocol#143]

**Comment by extremeheat** [comment]
Set the version to 1.17.30 and it should work. There were no protocol changes.

**Comment by MyNameInc** [comment]
> Set the version to 1.17.30 and it should work. There were no protocol changes.

I create a client, as a result, the error is the version is not supported

**Comment by extremeheat** [comment]
Update your dependencies
