### ISSUE TITLE
Servers don't run

### ISSUE THREAD

**Issue by jakeayy** [mhsjlw/pocket-minecraft-protocol#145]
Hello, while I am running server from [example folder](https://github.com/PrismarineJS/bedrock-protocol/blob/master/examples/server/basicServer.js) It doesn't work, it doesn't even show motd. What can I do?
Using latest (1.17.34) version of game

**Comment by extremeheat** [comment]
On what device? on windows see https://github.com/PrismarineJS/bedrock-protocol/blob/master/docs/FAQ.md

**Comment by jakeayy** [comment]
Thanks, it worked!
