### ISSUE TITLE
Minecraft 1.17.40

### ISSUE THREAD

**Issue by Peanutzy** [mhsjlw/pocket-minecraft-protocol#149]
May I ask when mc 1.17.40 will be supported?

**Comment by extremeheat** [comment]
It should be already. There are no protocol changes.

**Comment by Peanutzy** [comment]
Oh ok thanks. I'll try it later

**Comment by Peanutzy** [comment]
When i try joining a server with version 1.17.40.06 it says this error

Server requested disconnect: disconnectionScreen.outdatedClient

**Comment by extremeheat** [comment]
looks like there was protocol changes, closing as in favor of duplicate #146
