### ISSUE TITLE
Send `move_player` packet?

### ISSUE THREAD

**Issue by EchoHackCmd** [mhsjlw/pocket-minecraft-protocol#166]
Tried sending a `move_player` packet via the `client.queue();` method and it prints an error about `Cannot mix BigInt and other types, use explicit conversions`? am I missing something?

**Comment by ATXLtheAxolotl** [comment]
Could you provide the code that resulted in the error?

**Comment by EchoHackCmd** [comment]
const newPos = { x: localPlayerCache.position.x, y: localPlayerCache.position.y + 1, z: localPlayerCache.position.z };                client.queue('move_player', { runtime_id: client.entityId, position: newPos });

It's every time I include the `runtime_id` that it results in the error?

**Comment by extremeheat** [comment]
`client.entityId` is being written as a BigInt type, you need to write it as a Number with `Number(bigInt)`, (as in Start Game packet we get a 64-bit varint but Move Player requires a 32-bit varint)... We'll abstract these issues away soon with mineflayer.
