### ISSUE TITLE
Error processing LoginPacket: Required property "XUID"

### ISSUE THREAD

**Issue by LordBombardir** [mhsjlw/pocket-minecraft-protocol#168]
Hello. When trying to connect to the server via client.js the following error occurs: Bad packet (error ID 3fdc2892da79): Error processing LoginPacket: Required property "XUID" of class pocketmine\network\mcpe\protocol\types\login\AuthenticationData is missing in JSON data. How can this be solved?

**Comment by extremeheat** [comment]
Set `process.env.DEBUG = 'minecraft-protocol'` at the top of your code, rerun and post the log

Most likely you are not being authenticated properly

**Comment by LordBombardir** [comment]
> 

Thank you, I will definitely try

**Comment by LordBombardir** [comment]
> Set `process.env.DEBUG = 'minecraft-protocol'` at the top of your code, rerun and post the log
> 
> Most likely you are not being authenticated properly

Unfortunately, everything is also:(

**Comment by LordBombardir** [comment]
Made "offline: false". Now the error comes out: "Bad packet (error ID 888d298ac4e3): Error processing LoginPacket: JsonProperty "XUID" does not exist in object of type pocketmine\network\mcpe\protocol\types\login\clientData"

**Comment by extremeheat** [comment]
Cannot reproduce this issue. A separate issue with skins is fixed in #169 , if you continue to have this issue you need to provide the debug log

**Comment by extremeheat** [comment]
Closing, if you still have the problem please re open with more information
