### ISSUE TITLE
Packet Violation Warning

### ISSUE THREAD

**Issue by LuciaDX** [mhsjlw/pocket-minecraft-protocol#175]
When trying to join bedrock dedicated server through relay client sends packet_violation_warning with packet id 174 and client disconnects i guess thats something with new world format because e.g. pocketmine uses old chunk format and i can easily join it with relay

**Comment by extremeheat** [comment]
What server version is this? Are you on the latest bedrock protocol release? 

Have not seen any issues from testing 1.18.0, and our proxy CI is passing. Can you try on a fresh server instance to see if you can reproduce?

**Comment by LuciaDX** [comment]
Yes i tried joining local bedrock dedicated server and last packet that i got was packet violation i also tried joining hive through relay and got the same result. But when i tried joining fresh local pocketmine server  i succeeded

**Comment by extremeheat** [comment]
You haven't answered any of the questions

**Comment by LuciaDX** [comment]
Latest bedrock dedicated server 1.18.2

**Comment by extremeheat** [comment]
Run npm update

**Comment by extremeheat** [comment]
Is this still an issue on latest release, 3.10/Minecraft 1.18.10 ?

**Comment by extremeheat** [comment]
Hello

I'm going to assume this was fixed. Please re-open if it's still a problem with more information.
