### ISSUE TITLE
Fix this Error when the bot Join my Powernukkit LocalHost Server!!!

### ISSUE THREAD

**Issue by ProSteve12301** [mhsjlw/pocket-minecraft-protocol#177]
Please Fix this Error because i want to add an bot on my Server(24/7).
This is the Error i encountered:

![Screenshot_2022-02-07-15-57-53-16_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/79408961/152748116-a53009cf-f4a0-4c26-ab28-da8efe370c23.jpg)

**Comment by ProSteve12301** [comment]
On Server Log:
![Screenshot_2022-02-07-15-58-41-59_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/79408961/152748546-5961c127-e07b-4a74-9bcd-dfefc8531dd4.jpg)

**Comment by extremeheat** [comment]
Are all your dependencies up to date? `npm update --depth 9999`

Can a vanilla client join the server? It's possible this is a bug inside powernukkit, my guess is with their handling of shield IDs

**Comment by XDJames34** [comment]
Thanks!!!
