### ISSUE TITLE
Proxy MITM

### ISSUE THREAD

**Issue by frizib** [mhsjlw/pocket-minecraft-protocol#212]
Hi!

Is it possible to somehow use a proxy to substitute the names of gaming devices and other things?

**Comment by extremeheat** [comment]
Can you elaborate as to the issue or question (with an example)? I don't quite understand what you're asking about.

**Comment by LucienHH** [comment]
Sounds like you're looking for Relay. https://github.com/PrismarineJS/bedrock-protocol/blob/master/docs/API.md#proxy-docs

**Comment by frizib** [comment]
I would not refuse the sample code

**Comment by extremeheat** [comment]
Closing as not enough information here, please join discord or add more information on what you want to achieve (maybe a screenshot).
