### ISSUE TITLE
Help with the bot

### ISSUE THREAD

**Issue by Sasha20028** [mhsjlw/pocket-minecraft-protocol#219]
Hi! There are a couple of questions:

1) Is it possible to create a bot that can walk on coordinates?

2) Can I replace the name of the bot device? Usually writes Windows 10, I want something of my own. I have seen many places that this can be changed.

**Comment by extremeheat** [comment]
1. Yes - but without mineflayer, this will be complex as you need to write your own movement code & logic. #116 
2. In offline mode, yes, you can change username with "username" option. In online mode, the username is always the Xbox gamertag.

**Comment by frizib** [comment]
Not an alias, but the name of the device.

Was WIN10, will become with IOS
![image](https://user-images.githubusercontent.com/28644006/172046320-59c1a8b5-211a-4fc5-a40e-bb08a1686438.png)

**Comment by Sasha20028** [comment]
Is there a code example using "mineflayer"?

The essence of the connection is clear, but I don't understand how to make the code without errors:(

**Comment by Sasha20028** [comment]
Changing the "AuthTitle" did not help to remove the Windows 10 label.
![image](https://user-images.githubusercontent.com/52866621/172349531-c2a49cbd-ed65-495c-9445-c001d18553bf.png)

**Comment by LucienHH** [comment]
You'd need to modify the `DeviceOS` in the payload found here. https://github.com/PrismarineJS/bedrock-protocol/blob/52156a002473b9752e97bd13bf15a18645256667/src/handshake/login.js#L46
Possible values:
```json
{
  "0": "Undefined",
  "1": "Android",
  "2": "IOS",
  "3": "OSX",
  "4": "FireOS",
  "5": "GearVR",
  "6": "Hololens",
  "7": "Win10",
  "8": "Win32",
  "9": "Dedicated",
  "10": "TVOS",
  "11": "Orbis",
  "12": "NintendoSwitch",
  "13": "Xbox",
  "14": "WindowsPhone"
}
```

```js
const client = createClient(...)

client.session = {
  deviceOS: /* 1-14 */
}
```

**Comment by Sasha20028** [comment]
Can you help with 1 question?
Example of moving by coordinates.

**Comment by LucienHH** [comment]
As extremeheat mentioned you can move the client but it's a very complex task that will be much simpler to execute once Mineflayer integration is complete. You can check the progress here #116

**Comment by Sasha20028** [comment]
OK, thanks
