### ISSUE TITLE
createClient ping timeout on initialization will crash the app

### ISSUE THREAD

**Issue by lowlines** [mhsjlw/pocket-minecraft-protocol#220]
The initial (optional) ping done when the createClient is initialized doesn't catch the RakClient errors such as when the ping times out. This can happen occasionally when talking to lan games. Adding a bit of error handling will keep the app from crashing.

See https://github.com/lowlines/bedrock-protocol/commit/1ae9c0ef5e784024b85d4b0f5eda579e49cbfba5

**Comment by extremeheat** [comment]
#218

**Comment by extremeheat** [comment]
Fixed in 218
