### ISSUE TITLE
How to accept realms invite url?

### ISSUE THREAD

**Issue by anondiscord-noname** [mhsjlw/pocket-minecraft-protocol#228]
```json
{"errorCode":403, "errorMsg":"Not invited"}
```

**Comment by LucienHH** [comment]
Just tested this and seems to be working (joining a Realm I'm not in via invite). Can you run `npm update` and try again.

**Comment by anondiscord-noname** [comment]
updated
```
node_modules/bedrock-protocol/src/client/auth.js:28
  if (!realms || !realms.length) throw Error('Couldn\'t find any Realms for the authenticated account')
                                       ^

Error: Couldn't find any Realms for the authenticated account
```

**Comment by LucienHH** [comment]
Ah, I see the issue. I assume the account you're using hasn't joined any Realms before causing the initial fetch to throw an error as we don't receive any Realms however if you're joining via invite this fetch shouldn't be needed.

**Comment by anondiscord-noname** [comment]
Resolved, thank you!
