### ISSUE TITLE
Make bot move using move_player packet

### ISSUE THREAD

**Issue by squeaky2137** [mhsjlw/pocket-minecraft-protocol#229]
Hey! Ive been trying to make the bot walk using the move player / move entity packets but cant seem to get it to work.
I receive no errors and the bot doesnt leave or anything it just doesnt move

code

const newPos = { x: client.startGameData.player_position.x, y: client.startGameData.player_position.y, z: z };
            client.write('move_player', { runtime_id: Number(client.entityId), position: newPos, pitch: 0, yaw: 0, head_yaw: 0, mode: 0, on_ground: true, ridden_runtime_id: 0, tick: 0n });

**Comment by extremeheat** [comment]
Hi

You can ask these questions related to actions on Discord in the #bedrock room (also see the wiki post [here](https://github.com/PrismarineJS/bedrock-protocol/wiki/Using-bedrock-protocol)), but in short the correct packet to send depends on if the server is using 'Server Authoritative Movement' or not, sent in the login packet (so you use PlayerAuthInput vs MovePlayer).

**Comment by squeaky2137** [comment]
Ah ok thank you! And I will make sure to join the discord
