### ISSUE TITLE
Update dependencies for 1.19.10

### ISSUE THREAD

**Issue by ghost** [mhsjlw/pocket-minecraft-protocol#241]
Version 3.15.0 of bedrock-protocol depends on `minecraft-data` 3.9.0, but it's currently pointing to 3.0.0.

**Comment by extremeheat** [comment]
This is not a problem, npm uses semantic versioning. We use `^` prefix, so when doing npm install/update the latest update will be picked under the major version category of 3.

So ^3.0.0 = 3.10.0 (or any other 3.* version)
