### ISSUE TITLE
add_player packet not received on client

### ISSUE THREAD

**Issue by Sasha20028** [mhsjlw/pocket-minecraft-protocol#243]
Hi! I receive a MobEffect package from the server with the parameters:

runtime_entity_id: 436n, 
event_id: 1, 
effect_id: 10, 
amplifier: 200, 
particles: false, 
duration: 400

When sending the same package, I don't understand how to get\generate "runtime_entity_id".

**Comment by extremeheat** [comment]
Hello, can you elaborate on what you want to "generate"? Don't you already have the entity ID there you want, 436 ?

If you want to link that to a user you're going to need to keep track of players in the `add_player` packet.

**Comment by Sasha20028** [comment]
> Здравствуйте, можете ли вы подробнее рассказать о том, что вы хотите «генерировать»? Разве у вас уже нет идентификатора сущности, который вы хотите, 436 ?
> 
> Если вы хотите связать это с пользователем, вам нужно будет отслеживать игроков в пакете.`add_player`

Packet track from server to player or from player to server?

**Comment by Sasha20028** [comment]
> Hello, can you elaborate on what you want to "generate"? Don't you already have the entity ID there you want, 436 ?

436 is what I just get from the server. If I want to send a packet with this value, then nothing happens

> If you want to link that to a user you're going to need to keep track of players in the `add_player` packet.

Packet track from server to player or from player to server?

**Comment by extremeheat** [comment]
So you want to send this mob effect packet to the client, am I understanding correctly?

**Comment by Sasha20028** [comment]
> So you want to send this mob effect packet to the client, am I understanding correctly?

yes

**Comment by Sasha20028** [comment]
> > So you want to send this mob effect packet to the client, am I understanding correctly?
> 
> yes

Strange. When I log in from the PC, "add_player" does not come to the server. And when I connect from the phone, everything comes.

**Comment by Sasha20028** [comment]
Strange. When I log in from the PC, "add_player" does not come to the server. And when I connect from the phone, everything comes.

**Comment by extremeheat** [comment]
are you using a proxy or a server with bedrock-protocol?

**Comment by Sasha20028** [comment]
> are you using a proxy or a server with bedrock-protocol?

I downloaded the update `1.19.10` and the `add_player` package stopped coming to me.

On the previous version, the package did not come from the PC only, now it does not come from the phone every time

Package log: https://pastebin.com/HjHh52h8

**Comment by Sasha20028** [comment]
` > `Debug provided:

+ Connection from version 1.19.10 (PC)
+ PMMP Server (1.19.10)

` > `Actions on the server:
+ Log in to the server -> write to chat 123 -> log out from the server.

` > `[DEBUG](https://pastebin.com/1CnaVNxG)

**Comment by extremeheat** [comment]
Please provide your code and some screenshots of the problem and how it looks in game

**Comment by Sasha20028** [comment]
> Please provide your code and some screenshots of the problem and how it looks in game

+ Running a proxy server 
+ I log on to the server 
 
The `add_player` package is not logged

Code https://pastebin.com/qvevcTbi
![vNNW2kh0sOs](https://user-images.githubusercontent.com/52866621/181204553-1ec3be73-9d07-4a0b-b210-f9e912422a74.jpg)

**Comment by extremeheat** [comment]
Please re-open if this is still a problem on latest version, 1.19.50
