### ISSUE TITLE
Chat message writing error

### ISSUE THREAD

**Issue by InnateAlpaca** [mhsjlw/pocket-minecraft-protocol#255]
Hello! I'm getting an error while trying to queue text packets. 
(I used a regular client.queue('text', packet), which always worked before the update. 
There are also problems with offline-mode bots, as well as with the relay.

`While decoding  ea5c3b9530bef45d6cca6c63c8ffb0ef7d218e351dd7023d8492469825f2718e22c6bcb269769b7c9195bb1b969710e46c4f970
Client failed to read packet TypeError [ERR_INVALID_ARG_TYPE]: SizeOf error for 
undefined : The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined`

**Comment by extremeheat** [comment]
Can you provide the code that can reproduce this issue ?

**Comment by InnateAlpaca** [comment]
...
`client.queue('text', {
            type: 'chat',
            needs_translation: false,
            source_name: 'username',
            message: 'hello',
            xuid: ''
})`
or idk... I tried several changes to the packet to see if that could solve the error.

**Comment by extremeheat** [comment]
You are missing fields in that. The fields for a chat message are listed in the README.

**Comment by InnateAlpaca** [comment]
I'm sry, have you tried to queue a message, and managed to without any problem (using all correct parameters)?
I have tried all possible combinations of parameters and always got that error... yea in that one I'm missing an undefinied parameter ok, but I also tried it with it.

**Comment by extremeheat** [comment]
Why the close? Was this a problem on your side?

**Comment by InnateAlpaca** [comment]
yes
