### ISSUE TITLE
How to fix error

### ISSUE THREAD

**Issue by middle1** [mhsjlw/pocket-minecraft-protocol#257]
root@localhost:~# npm install bedrock-protocol
npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path /root/.npm/_cacache/tmp/74d8f717
npm ERR! dest /root/.npm/_cacache/content-v2/sha512/36/c6/13346dd748d41330d5aa3faaf15fc4f92faa5531e43d0051844f1051e86d55151f1ec93560b1b19a7bcaf02e9a101b01fc9b434b21954dc20f1951a8281a
npm ERR! errno ENOENT
npm ERR! enoent Invalid response body while trying to fetch https://registry.npmjs.org/uuid: ENOENT: no such file or directory, rename '/root/.npm/_cacache/tmp/74d8f717' -> '/root/.npm/_cacache/content-v2/sha512/36/c6/13346dd748d41330d5aa3faaf15fc4f92faa5531e43d0051844f1051e86d55151f1ec93560b1b19a7bcaf02e9a101b01fc9b434b21954dc20f1951a8281a'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-08-15T19_48_34_095Z-debug-0.log

**Comment by extremeheat** [comment]
Reinstall nodejs and npm

**Comment by middle1** [comment]
tried already, i install 14.20.0 version with nvm

> Переустановите nodejs и npm

**Comment by extremeheat** [comment]
Try a different folder. This is not an issue with bedrock protocol.

**Comment by middle1** [comment]
Okay, but when you start the bot with this code:
`const bedrock = require('bedrock-protocol')
const client = bedrock.createClient({
  host: 'localhost',
  port: 19132,        
  username: 'Tester123', 
  offline: true       
})
`
It writes an error to the console:
`[RakLib thread/NOTICE]: Blocked 127.0.0.1 for 5 seconds
 [RakLib thread/ERROR]: Bad packet from 127.0.0.1 46912: Not enough bytes left in buffer: need 8, have 5`
I have a Minecraft server PocketMine-MP 1.19.10
