### ISSUE TITLE
Client not connecting to PocketMine server

### ISSUE THREAD

**Issue by middle1** [mhsjlw/pocket-minecraft-protocol#260]
I have a problem when I start the bot on my server (PocketMine-MP 1.19.10), then in the server console I write a packet error:
`[RakLib thread/ERROR]: Bad packet from 127.0.0.1 44294: Not enough bytes left in buffer: need 8, have 5
 [RakLib thread/NOTICE]: Blocked 127.0.0.1 for 5 seconds`
how to fix this error?

**Comment by extremeheat** [comment]
Cannot reproduce. Please provide the PocketMine version.

**Comment by extremeheat** [comment]
Too old, closing. Please reopen if this is still a problem and you have more information.
