### ISSUE TITLE
unable to connect to a server using the relay

### ISSUE THREAD

**Issue by goggle12345** [mhsjlw/pocket-minecraft-protocol#269]
i get disconnected every time i try to join a server through the relay, i have tried multiple different servers. 
![disconnected](https://user-images.githubusercontent.com/112666108/188023414-90e308d8-70fe-41b5-8c17-de8f853530be.PNG)
![disconnected2](https://user-images.githubusercontent.com/112666108/188023632-fdb80a8f-7358-4279-8df6-46a22e4327d5.PNG)

**Comment by extremeheat** [comment]
Please provide the code you are using and set the "logging" option to true in relay options and provide a complete log of the console (not an image)

**Comment by goggle12345** [comment]
Creating relay
Listening on 127.0.0.1 19032 1.19.21
New connection from 127.0.0.1/61333
* Client -> Proxy login {"protocol_version":534,"tokens":{"identity":"{\"chain\":[\"eyJhbGciOiJFUzM4NCIsIng1dSI6Ik1IWXdFQVlIS29aSXpqMENBUVlGSzRFRUFDSURZZ0FFQz
ZlSXd1MENlenlrZC81enVoTEw0UUYvTVViVVcyVXFkbHdZMWdsWjZCUCswR25oMWwv
* Proxy -> Client server_to_client_handshake {
  token: 'eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCIsIng1dSI6Ik1IWXdFQVlIS29aSXpqMENBUVlGSzRFRUFDSURZZ0FFMjQwOTdsQ09SZU9nMyt1QmZnb0lmbkViZkF2cWZXcXdDaitLZ256TEt5QTNM
OXFtblUxNGFYWkJDbTRIV01rZjR6N1Y4RnE4b2ZYL3RnaklDVXBwNVJ3TjA2WEtlVUJlbHlmVDQ0Q2RMQUFTRnBycW1nQk10Mi9yYkVjMXZFQW0ifQ.eyJzYWx0IjoiOEorbmdnPT0iLCJzaWduZWRUb2tlbiI
6Ik1IWXdFQVlIS29aSXpqMENBUVlGSzRFRUFDSURZZ0FFMjQwOTdsQ09SZU9nMyt1QmZnb0lmbkViZkF2cWZXcXdDaitLZ256TEt5QTNMOXFtblUxNGFYWkJDbTRIV01rZjR6N1Y4RnE4b2ZYL3RnaklDVXBwN
VJ3TjA2WEtlVUJlbHlmVDQ0Q2RMQUFTRnBycW1nQk10Mi9yYkVjMXZFQW0iLCJpYXQiOjE2NjIwNzE5Njh9.UQN9AFKHqQRVySssQ-B6hE5acYaFuxpXly0_d0VdnZJVywH29qs5KmTiiKq7I2CYTZX0QaXDFR
Lq5lUvoaKimclraIV1kBXC6Fmzy0ko4Y5sT4UgReWWoShFnx2iKpsk'
}
* Client -> Proxy Started encryption <Buffer 18 6a 15 b9 cd 3f 45 96 10 67 dc ec 1e b5 0d 34 ea ad 33 d7 0c 42 ff 90 80 f7 c9 76 64 d5 86 e2 1f 7e c7 e5 28 12
 dd 7c b4 36 ea b1 0a d2 be 83> <Buffer b4 f2 91 17 ac fd 28 f3 2a c4 4f 1e 4b 6f 0f d6>
Connecting to mco.mineplex.com 19132

* Client -> Proxy client_to_server_handshake {}
* Proxy -> Client play_status { status: 'login_success' }
* Proxy -> Client Flushing downstream queue
* Client -> Proxy Got downstream connected packet but upstream is not connected yet, added to q {
  data: { name: 'client_cache_status', params: { enabled: true } },
  metadata: { size: 3 },
  buffer: <Buffer 81 01 01>,
  fullBuffer: <Buffer 81 01 01>
}
* Proxy -> Backend login {
  protocol_version: 545,
  tokens: {
    identity: '{"chain":["eyJhbGciOiJFUzM4NCIsIng1dSI6Ik1IWXdFQVlIS29aSXpqMENBUVlGSzRFRUFDSURZZ0FFcThheGY3T1IrNWsveDRCOGsxck02ajVxMWVFTTVkOGg2aU9rM3liSTlhTm1B
dVRFMTF1NW52anF3S09pV2gvOGlEalJ0VFEvbHREYU5rN09WMlU5M3UrTThyWHorSUFscW13WkNwQU1SQWtlcFhrRjZxNTkxbityRVF3VXE2bE4ifQ.eyJpZGVudGl0eVB1YmxpY0tleSI6Ik1IWXdFQVlIS29
aSXpqMENBUVlGSzRFRUFDSURZZ0FFOEVMa2l4eUxjd2xacnlVUWN1MVR2UE9tSTJCN3ZYODNuZG5XUlVhWG03NHdGZmE1Zi9sd1FOVGZyTFZIYTJQbWVucEdJNkpoSU1VSmFXWnJqbU1qOTBOb0tORlNOQnVLZ
G04cllpWHNmYXozSzM2eC8xVTI2SHBHMFp4Sy9WMVYiLCJjZXJ0aWZpY2F0ZUF1dGhvcml0eSI6dHJ1ZSwiaWF0IjoxNjYyMDcxOTY5fQ.NHzR3ESls8zpi_Qyqf-UCjXnIAd-lpn_KQchPY68O2A6vj5Exxfe
rCjADEsuqfP9ppiWzIYxtm0d0niwcMiSkmhCiO2uCjcRVLhPMKC07SodoUXQ9HANqsJL7F7rfo9V","eyJ4NXUiOiJNSFl3RUFZSEtvWkl6ajBDQVFZRks0RUVBQ0lEWWdBRThFTGtpeHlMY3dsWnJ5VVFjdTF
UdlBPbUkyQjd2WDgzbmRuV1JVYVhtNzR3RmZhNWZcL2x3UU5UZnJMVkhhMlBtZW5wR0k2SmhJTVVKYVdacmptTWo5ME5vS05GU05CdUtkbThyWWlYc2ZhejNLMzZ4XC8xVTI2SHBHMFp4S1wvVjFWIiwiYWxnI
joiRVMzODQifQ.eyJuYmYiOjE2NjIwMzEwNTMsInJhbmRvbU5vbmNlIjo4OTQ4NDU3NTI0NjA3NjMwMTQ0LCJpc3MiOiJNb2phbmciLCJleHAiOjE2NjIyMDM5MTMsImNlcnRpZmljYXRlQXV0aG9yaXR5Ijp0
cnVlLCJpYXQiOjE2NjIwMzExMTMsImlkZW50aXR5UHVibGljS2V5IjoiTUhZd0VBWUhLb1pJemowQ0FRWUZLNEVFQUNJRFlnQUV1STFpbjlwbW11NUtQMDJKMHVZZnlKYTFJRVVzbklMR0FLT1IyTHNrdTgwNl
wvTElmNGxPQ1N3UHg0UWVzMnFrMTJNNW1mcE15ZGRNdlZjUzd0cUJNc2FJenR4Y3EwTlhxckVjWHVMTlhZUmRIeW1EYjJyRFk2VmtmZktVdkErSmsifQ.Xs8mRc6Bv5Ht3F3xqJHUvvx6V3Qlb6sofIEezq1cH
ipJJo58LLh1G5jQNvjX8W3tCQELE5uXl9IQewzdi8LO50aJCpNkzbqddnZ4G4rs6Lc4ojchBlBnTvfPeRzr6KAx","eyJ4NXUiOiJNSFl3RUFZSEtvWkl6ajBDQVFZRks0RUVBQ0lEWWdBRXVJMWluOXBtbXU1
S1AwMkowdVlmeUphMUlFVXNuSUxHQUtPUjJMc2t1ODA2XC9MSWY0bE9DU3dQeDRRZXMycWsxMk01bWZwTXlkZE12VmNTN3RxQk1zYUl6dHhjcTBOWHFyRWNYdUxOWFlSZEh5bURiMnJEWTZWa2ZmS1V2QStKay
IsImFsZyI6IkVTMzg0In0.eyJuYmYiOjE2NjIwNzE5MDksImV4dHJhRGF0YSI6eyJYVUlEIjoiMjUzNTQxNDEzNjM1MzY1MyIsImlkZW50aXR5IjoiN2YzM2RhNTEtMTM2MS0zZDI2LTk0ODctMGUwYTc1NmNk
MzY2IiwiZGlzcGxheU5hbWUiOiJTdGFyQXhpczY1NTk4NDEiLCJ0aXRsZUlkIjoiMjA0NzMxOTYwMyJ9LCJyYW5kb21Ob25jZSI6LTU4NTc3NDE2OTczMTM1MzI5ODEsImlzcyI6Ik1vamFuZyIsImV4cCI6MT
Y2MjE1ODM2OSwiaWF0IjoxNjYyMDcxOTY5LCJpZGVudGl0eVB1YmxpY0tleSI6Ik1IWXdFQVlIS29aSXpqMENBUVlGSzRFRUFDSURZZ0FFcThheGY3T1IrNWtcL3g0QjhrMXJNNmo1cTFlRU01ZDhoNmlPazN5
Ykk5YU5tQXVURTExdTVudmpxd0tPaVdoXC84aURqUnRUUVwvbHREYU5rN09WMlU5M3UrTThyWHorSUFscW13WkNwQU1SQWtlcFhrRjZxNTkxbityRVF3VXE2bE4ifQ.KMMxefXsU3kjjcxAHUeP6wkFcv_oAyg
PFMdCUHIhO0DtGR7bAlBHcHluqSYnyvU7-dEPpF0Q292WJXozYayfHqF-7efKIbvdBGHx9zL3CywlOlaNzePiddCQzqRYq2EL"]}',
    client: 'eyJhbGciOiJFUzM4NCIsIng1dSI6Ik1IWXdFQVlIS29aSXpqMENBUVlGSzRFRUFDSURZZ0FFcThheGY3T1IrNWsveDRCOGsxck02ajVxMWVFTTVkOGg2aU9rM3liSTlhTm1BdVRFMTF1NW52a
nF3S09pV2gvOGlEalJ0VFEvbHREYU5rN09WMlU5M3UrTThyWHorSUFscW13WkNwQU1SQWtlcFhrRjZxNTkxbityRVF3VXE2bE4ifQ.eyJBbmltYXRlZEltYWdlRGF0YSI6W10sIkFybVNpemUiOiIiLCJDYXBl
RGF0YSI6IiIsIkNhcGVJZCI6IiIsIkNhcGVJbWFnZUhlaWdodCI6MCwiQ2FwZUltYWdlV2lkdGgiOjAsIkNhcGVPbkNsYXNzaWNTa2luIjpmYWxzZSwiUGVyc29uYVBpZWNlcyI6W10sIlBlcnNvbmFTa2luIj
pmYWxzZSwiUGllY2VUaW50Q29sb3JzIjpbXSwiUHJlbWl1bVNraW4iOnRydWUsIlNraW5BbmltYXRpb25EYXRhIjoiIiwiU2tpbkNvbG9yIjoiIzAiLCJTa2luSWQiOiIzNzQzMjcyOC1hYWI3LTQ5YjAtOTVi
NC05ZmU1MDMyMzU1NjAuU3Bvb2t5U3Bpcml0IiwiU2tpbkltYWdlSGVpZ2h0IjoxMjgsIlNraW5JbWFnZVdpZHRoIjoxMjgsIlNraW5SZXNvdXJjZVBhdGNoIjoiZXdvZ0lDQWlaMlZ2YldWMGNua2lJRG9nZX
dvZ0lDQWdJQ0FpWkdWbVlYVnNkQ0lnT2lBaVoyVnZiV1YwY25rdWFIVnRZVzV2YVdRdVkzVnpkRzl0SWdvZ0lDQjlDbjBLIiwiU2tpbkRhdGEiOiIvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93
RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BTXZZemYvTXp0ci92N3UrLzc3QXh2Kzd5c3IvdnNDNi84ckR5Zi9Dd3I3L3U4ckEvNzYreS8vSnc4bi92c3pHLzhxOH
lQKzd4TVQveTlYVy85SEt6Zis3eDhuL3hjSEsvOFM3di8vQ3g3di92TU82LzhqQncvL0p5TC8veDhHOS84Qzh4UCs5d3NYL3Y3KzYvNzI3d1AvSXdjSC93N3ZELzhHOHhQL0l3TWovL3dEL0FQOEEvd0QvQVA4
QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQV
A4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQUx2RnUvL0t5OVQvMXNyWC85ckwyZi9Uek5QLzBOREwvODdQei8vTTE5Yi8xOHpTLzg3UXp2L1kyZFgvdk1iQy8vOEEvd0Qv
QVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0
QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEv
d0QvQVA4QS93RC9BUDhBL3dEL0FQOEExYzNWLzh1L3ZmKzl2OG4vekwrKy84dkJ2ZisvdTh2L3dzYkovNzYrdlArK3lNYi91OGUrLzhMS3YvL0N6TDMveU1ISC83M0R5UC9JdnI3L3k5YlUvOG0vdmYvTXpMdi
95cjNELzh5OHd2L012OFgvd2NDOC84Tyt3UCs4dk1IL3ZNQzkvOE83eHYvSng4RC92Y3pJLzcvRXlmKzl3NzcveDhERi84Zkp3di8vQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQ
OEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0
FQOEEvd0QvQVA4QS93Qy94Y24veXNhOC83N0F1di9WMk1uL3p0ck8vOWJYei8vUHpkTC8wZFBNLzlET3ovL1J6c3ovMGMzVy84ekt4UCs3dmNUL3ZjYkkvLzhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dE
L0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3
dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RFUyYy8v
ek1QRS84akd4Lys5d01uL3ZidkUvOEM5dS8vTHpNbi93TC9LLzhqTXlQL0l3cjMvd2NMQS83L0x3disvdnIzL3pMdTcvOGEreC8vUzBkTC95TVBHLzhmRHkvL0R4cnovd2NISy84bkN2di9FeXNQL3ZidTcvOG
03eHYvTHpNVC96TDNELzhMR3gvL0h3Y2ovd01iQS84akx4di9LeDczL3dzaTkvLzhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9B
UDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBdThySC84YkF2Ly9Gd3NYL3hzRE
gvOHZHdy8vS3pOZi8yZFhTLzhyTnlmL1B5dGIveXNuTi84N1B6UCs5dmI3L3dzSEgvOERMeXYvSXpMMy94THpJLy84QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93

RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS
93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FNSEJ5disreEx2L3c4SzgvOFBIeWYvSHhNUC93TXJBLzhQ
SngvL0V3Y3Yvd2NIRS84Ry91di9BeGNML3hyMjYvOGZEeHYvSHhzai92TURBLzhXL3hmL0h2OEgvdTh2Sy84SEJ4Ly9Idkx6L3U4dkcvOGZKdi8vQ3U4ai92Y1hLLzhyQnZmKyt2Y2Yvd0x5OC83Mjl2di9JdT
hyL3ZjSEgvOG5FeS8vQXg3di8vd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0Qv
QVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0M4d2NILzFjck4vOGUveC8vTXZjbi94YnZGLzgvSzAvL0x6c3IvemN6YS85VFMydi
9OMWRMLzI5akovOExFdmYvQ3Zjai92TVBJLzlUVzF2Kzd5OFQvL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEv
d0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOE
Evd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QXdMdTcvOEc3dy8vSnlyLy94Y1RDLzhmRHZmL0F2OGovdnNYQi84YkF4Zi9IeE12L3ZMdkovOHk3dlAvRHU3
Ly93THZLLzhYSXZQL0N2cjMvdzczQy84VEd4Zi9Dd2NIL3dieSsvNy9MeWYrOXU4Yi93Y25MLzhxL3kvL0J6THIvdmNqQi84bkJ5Ly9Hdk1YL3pMMjgvOEM5eFAvTXlMei93Y3JDLzd5OXZmLy9BUDhBL3dEL0
FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dE
L0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BTXJYeWYvSzFOWC94Y0xILytUaTNmL0Z4c2YvMjlqVC85UEwyUC9XMTlYLzJOVFgvOXZOMFAvT3pzei91OGk4LzlmVDF2L0d2OEwvMj
lYVS85ZlAwUC8vQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhB
L3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUD
hBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dESndjUC93OFBLLzd6QXd2Kzl5OG4vdThLNi83N0d4UCs4eU1mL3dzbSsvOERBeS8vTHhjbi91NzNLLzhhN3lQL0J5TUQveXNuQy84dkV3Zis5dmNiL3ZjWEQv
NzNMeWYvRHhyLy91OFRKLzhmSHZmL0x4THIvdk1USy84bkJ4di9Ld01mL3didkwvOGJIdlAvRXdNSC94NzdDLzh5OHh2Ky95c0gvdmNYRi8vOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC
9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93
RC9BUDhBL3dEL0FQOEF6dFhOLzlmUTB2L0h2c3YvMStMWi83dTh1Lys4eHNuL3pkSFYvODdZMHYvV3pNei8wZEhKLzhqQXZ2Kzd2OFAvMU5YZi83M0d2di9NME5yLzJjL1ovLzhBL3dEL0FQOEEvd0QvQVA4QS
93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4
QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQU
wvTXV2Kyt3N3oveTh6TC84aTd2Ly9KdTc3L3U3M0YvOERIeFAvSHg3ei95c0hDLzd6R3ZQKyt4ci8vdmNMTC83ekN4UC9IdnJyL3lydTgvOGEreWYvQ3U3Ly94Y1hHLzhiSXgvL0F4TW4vdnIzSi84ekh1Ly9G
eUxyL3g3M0wvN3kveGYvRHhNRC93OHpILzhERXZQL0h4OGIveXI2OS84REp3Zis5eGNULy93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0
QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93REwwdGovMDhuVS85UFkw
di9qMytQLzR1TFIvOFhId2YvTTJOTC8xc3pZLzluWnlmL1h5OVAvdjhIRS85Zlk0UC9nNE96LzJzelEvOVBUMlAvUHlkVC8vd0QvQVA4QS93RC9BUDhBL3dEL0FNWEp1di9Cd2NYL3dzWEYvNzNJdmYvQnc3di
93Y1hFLzcvRHlQL0V4TUQvL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQ
OEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBdTc2OC84VEd2UC9Gdjh2L3ZzeTYvOHZKdnYvSH

pMci95Y25KLzcvRngvKzd3c0gveGIzTC83M0x4Ly9KeHI3L3lNdTkvOEhEdlAvSHdNTC91OExGLzc2N3UvKzl3NzcveWI2Ly83L0V3Lys4d3NiL3k3dkUvOHpMeC8vQnc4UC92TW5DLzhpOXgvL0F5c0QveHNX
OS83M0x2di9DdmNML3dzZTgvOFRFdXYvL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3
dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FOclcwdi9ReXRyLzB0YlgvK0RyNlAvVTRPSC93NzNBLzlQVHpQL1gwTXIv
MjlMUC85dkt6Zi9Cek1qLzN0dmEvKzN0My8vTHpjMy8wTmpSLzgzT3p2Ly9BUDhBL3dEL0FNWEp5Ly9Jd3NMLzA5WE4vODNMMnYvWTJOYi8yTlRaLzliVDJ2L1N5ZGYvME5uTC85SEoxUC9KdThyL3hNbkovLz
hBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9BUDhBL3dEL0FQOEEvd0QvQVA4QS93RC9B
  hide_disconnect_reason: false,
  message: 'Failed to connect to target server!'
}
* Proxy -> Client Q <-  disconnect {
  hide_disconnect_reason: false,
  message: 'Failed to connect to target server!'
}
* Proxy -> Client disconnect {
  hide_disconnect_screen: false,
  message: 'Backend server closed connection'
}
Kicked  127.0.0.1/61333 Backend server closed connection
player disconnected 127.0.0.1/61333 undefined
close connection 127.0.0.1/61333 undefined

**Comment by goggle12345** [comment]
const { Relay } = require('bedrock-protocol')

function createRelay () {
  console.log('Creating relay')
  const relay = new Relay({

    host: '127.0.0.1',
    port: 19032,
    offline: false,
    logging: true,
    
    destination: {
      host: 'mco.mineplex.com',
      port: 19132,
      offline: false,
      authTitle: "1"
    }
  })
  relay.conLog = console.debug
  relay.listen()
}

createRelay()

**Comment by extremeheat** [comment]
When posting large amounts of data you should use a pastebin service. For code https://gist.github.com is a good source. 

When embedding code on GitHub, use three backtick ` characters preceding and following a code block. This will format the code properly instead of a creating a disorganized comment as you see above.

**Comment by goggle12345** [comment]
https://gist.github.com/goggle12345/ea0afb871bb30a6890806a256a1eace3
not all of the log was show in command prompt, i think it was too long.

**Comment by goggle12345** [comment]
``` const { Relay } = require('bedrock-protocol')

function createRelay () {
  console.log('Creating relay')
  /* Example to create a non-transparent proxy (or 'Relay') connection to destination server */
  const relay = new Relay({
    /* host and port for clients to listen to */
    host: '127.0.0.1',
    port: 19032,
    offline: false,
    logging: true,
    /* Where to send upstream packets to */
    destination: {
      host: 'mco.mineplex.com',
      port: 19132,
      offline: false
    }
  })
  relay.conLog = console.debug
  relay.listen()
}

createRelay()
 ```

**Comment by extremeheat** [comment]
If the output is too long you need to redirect standard output to a file. 

node file.js > log.txt

**Comment by goggle12345** [comment]
https://gist.github.com/goggle12345/9b660c8e96b6641b8bea05065050f0fd

**Comment by extremeheat** [comment]
Cannot reproduce, on 1.18.0

![image](https://user-images.githubusercontent.com/13713600/188039695-78bb5667-dc36-4938-afd4-d639cd2bb733.png)

**Comment by goggle12345** [comment]
even when i try on 1.18.0.2 it still doesn't work

**Comment by extremeheat** [comment]
update your dependencies `npm update --depth 9999`

**Comment by goggle12345** [comment]
that fixed it! thank you for your help
