### ISSUE TITLE
Bot can't perform sleep action because id is not readable

### ISSUE THREAD

**Issue by Krukeletto** [mhsjlw/pocket-minecraft-protocol#270]
I wanted to create bot that would perform sleep action, to do it I need id of that bot. Even when I give the right id I still get an error

## My code:
 ```js
const bedrock = require('bedrock-protocol')
const client = bedrock.createClient({
  realms: {
    pickRealm: (realms) => realms[0]
    }
})

client.on('join', () => { // The client has joined the server.
    // client.on('start_game', console.log)
    client.queue('player_action', { action: 5, runtime_entity_id: 4294967295, position: 0, face: 0 })
})
```

## Error:
https://pastebin.com/BEpFfvf0

**Comment by extremeheat** [comment]
You are serializing the packet wrong. `position: 0` is not valid ; it must contain proper coordinates.

See the protocol documentation https://minecraft-data.prismarine.js.org/?v=bedrock_1.19.21&d=protocol#packet_player_action

**Comment by Krukeletto** [comment]
Well, now I have correct cordinates but I still get an error : / 

```js
const bedrock = require('bedrock-protocol')
const client = bedrock.createClient({
  realms: {
    pickRealm: (realms) => realms[0]
    }
})

const position = {
      x: 181,
      y: 58,
      z: 2926
}

client.on('join', () => { 
    // client.on('start_game', console.log)
  client.queue('player_action', {
    action: 5,
    runtime_entity_id: 4294967295,
    position: position,
    face: 0
  })
})
```

maybe I'm doing something wrong again but according to the docs I don't think so
