### ISSUE TITLE
Experiments don't work when joining through relay

### ISSUE THREAD

**Issue by LuciaDX** [mhsjlw/pocket-minecraft-protocol#289]
I use experimental query that only works when upcoming creator features enabled. Maybe mojang changed the way how they send experiments?
![scr1](https://user-images.githubusercontent.com/82135652/192136059-67aa14fb-0708-4791-a06e-e216250aa2aa.jpg)
![scr2](https://user-images.githubusercontent.com/82135652/192136064-880b5566-6b46-4ac0-b055-d495a3adce78.jpg)

**Comment by extremeheat** [comment]
I don't see any changes to experiments in https://github.com/PrismarineJS/minecraft-data/pull/631. Did this work on older versions (1.19.20)?

**Comment by LuciaDX** [comment]
Yes it did work properly on 19.21 and 19.22

**Comment by LuciaDX** [comment]
It seems like this is broken everywhere. In PM, in gophertunnel and here

**Comment by extremeheat** [comment]
Please open your project folder and go to `node_modules/bedrock-protocol/src/relay.js` and update the line here

https://github.com/PrismarineJS/bedrock-protocol/blob/131733fb5ae5234ff0ceb54968662870c89809e5/src/relay.js#L7 

to read `const debugging = true` and see if you can reproduce the issue

**Comment by LuciaDX** [comment]
Still doesn't work, maybe mojang changed something idk?
![image](https://user-images.githubusercontent.com/82135652/192236348-296cddb4-a851-4c80-99c2-b2f70432defc.png)

**Comment by extremeheat** [comment]
Can you confirm if this is still a problem on 1.19.50 ? Thanks.

**Comment by LuciaDX** [comment]
No, everything works fine now thank you
