### ISSUE TITLE
WaterDogPE proxy server transferring support

### ISSUE THREAD

**Issue by AnyBananaGAME** [mhsjlw/pocket-minecraft-protocol#299]

**Comment by AnyBananaGAME** [comment]
It doesn't support waterfog pe server transferring

**Comment by extremeheat** [comment]
Please provide the code, the expected functionality and the actual functionality.

**Comment by AnyBananaGAME** [comment]
Doesn't matter on my code, it joins the server fine. But the server uses a proxy that can switch between servers like if it was a dimension. And when it tries to transfer the bot becomes invisible and gets stuck on the NETHER screen

**Comment by AnyBananaGAME** [comment]
I did get the switch dimension packet 
It changed to nether but didn't change to overworked again

**Comment by extremeheat** [comment]
I'm not understanding your issue. You're making an issue inside the bedrock-protocol repository. This library allows you to create clients and servers for Minecraft Bedrock Edition. It does not implement any behavior minus basic boilerplate necessary for joining a server or handling a client. (Or perhaps you are referring to the Relay? We don't intercept any transfer packets and forward them directly, this could be an added feature in a PR. )

If you would like additional behaviors you will need to implement that yourself. See https://github.com/PrismarineJS/bedrock-protocol/wiki/Using-bedrock-protocol for more information. 

I'll close if this and move to a discussion if this is a general support question and not an issue with the library.

**Comment by AnyBananaGAME** [comment]
Well I don't think it can be done by clients, I think it has to supported by bedrock protocol first,

You can test it  for better understanding on Aetherpe.net by making an island and trying to do /is go

**Comment by extremeheat** [comment]
Closing as not enough information provided. If you have more information like code, expected and actual behavior to add please reopen.
