### ISSUE TITLE
Enchantment table not available to craft in crafting table when using proxy

### ISSUE THREAD

**Issue by bentonjj** [mhsjlw/pocket-minecraft-protocol#326]
Using 1.19.50 (not sure about earlier releases) enchantment table is not listed or can be crafted from crafting table when connecting to a bedrock server via proxy.

**Comment by extremeheat** [comment]
Is the server a vanilla server?

**Comment by bentonjj** [comment]
Lifeboat Survival Mode. Think it uses Pocketmine-MP.

**Comment by extremeheat** [comment]
Does this happen on a vanilla server also?

**Comment by bentonjj** [comment]
No did not seem to be an issue with the vanilla bedrock server, only an issue with Pocketmine-MPOn Dec 9, 2022, at 8:22 PM, extremeheat ***@***.***> wrote:﻿
Does this happen on a vanilla server also?

**Comment by extremeheat** [comment]
Is this still an issue on 1.19.62?

**Comment by extremeheat** [comment]
No updates, closing. Please reopen if this is still an issue.
