### ISSUE TITLE
Disconnecting from server after some time

### ISSUE THREAD

**Issue by Luluiscool** [mhsjlw/pocket-minecraft-protocol#329]
When i try to connect to a server it shows this message after some time

**Server requested disconnect: You are sending too many packets**

What the heck do i do?

**Comment by extremeheat** [comment]
Send less packets?

You need to provide an example to reproduce if you think this is a problem in bedrock-protocol.

**Comment by extremeheat** [comment]
Closing as no further information provided, reopen if you have information to add
