### ISSUE TITLE
logout from authentication

### ISSUE THREAD

**Issue by kadekedwin** [mhsjlw/pocket-minecraft-protocol#330]
how to logout from microsoft account that autenthicated?

**Comment by LucienHH** [comment]
You can change the bot's username or delete the cached tokens, token are stored in `.minecraft` within a folder called `nmp-cache`.

**Comment by kadekedwin** [comment]
> 

![image](https://user-images.githubusercontent.com/71983420/209819947-08a5d48b-8333-40ee-8f6d-5a7bca85074a.png)
can you please give me the complete path?

**Comment by Jarco-dev** [comment]
I'd normally be directly in the npm-cache folder afaik

> > 
> 
> ![image](https://user-images.githubusercontent.com/71983420/209819947-08a5d48b-8333-40ee-8f6d-5a7bca85074a.png) can you please give me the complete path?

**Comment by kadekedwin** [comment]
> I'd normally be directly in the npm-cache folder afaik
> 
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/71983420/209819947-08a5d48b-8333-40ee-8f6d-5a7bca85074a.png) can you please give me the complete path?

can you please give a screenshot?

**Comment by Jarco-dev** [comment]
> > I'd normally be directly in the npm-cache folder afaik
> > > > 
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/71983420/209819947-08a5d48b-8333-40ee-8f6d-5a7bca85074a.png) can you please give me the complete path?
> 
> can you please give a screenshot?

I'd rather not as I don't know if the id's in the file names are linked to anything or just random

But it's just a bunch of .json files that end with cache in the name. Located in the folder you showed inside the screenshot (the one you're in not one of the ones that you can see on it)

**Comment by LucienHH** [comment]
The path for a Windows env would be `%appdata%\.minecraft\nmp-cache`

**Comment by kadekedwin** [comment]
> The path for a Windows env would be `%appdata%\.minecraft\nmp-cache`

haha🤣, i think you are typo, it work thanks so much
