### ISSUE TITLE
error: ping timeout

### ISSUE THREAD

**Issue by duplicate2991** [mhsjlw/pocket-minecraft-protocol#343]
/home/runner/uuuu/node_modules/bedrock-pr otocol/src/rak.js:61 }, timeout, () => { throw new RakTime out('Ping timed out') })

RakTimeout [Error]: Ping timed out at /home/runner/uuuu/node_modules/bed rock-protocol/src/rak.js:61:31 at waitFor (/home/runner/uuuu/node_mo dules/bedrock-protocol/src/datatypes/util .js:30:32) Emitted 'error' event on Client instance at:

**Comment by AnyBananaGAME** [comment]
The server you are trying to join probably is offline

**Comment by duplicate2991** [comment]
> The server you are trying to join probably is offline

no seever was online

**Comment by AnyBananaGAME** [comment]
That error is given when the server is offline or it cant reach it
