### ISSUE TITLE
Fix errors in type definitions

### ISSUE THREAD

**Issue by hvlxh** [mhsjlw/pocket-minecraft-protocol#369]
Types are really broken, some class or functions doesn't have member variables or functions something. There is a tool called [dts-gen](https://github.com/Microsoft/dts-gen) that will generate d.ts files from any Javascript object. Please use this i guess

**Comment by extremeheat** [comment]
Can you elaborate beyond "types are really broken"? Please be specific with examples where the types are incorrect or do not align with the documented API.md. Automated generation tools are not appropriate.

**Comment by hvlxh** [comment]
> Can you elaborate beyond "types are really broken"? Please be specific with examples where the types are incorrect or do not align with the documented API.md. Automated generation tools are not appropriate.

Some that i noticed:
1. ServerAdveristement: expected 0 but received 3 (there is 3 parameters though)
2. client.getUserData() not defined
3. some more on client like connection, etc
4. ServerOptions: asking optional options but there are required

**Comment by hvlxh** [comment]
clicked close with comment accidentally

**Comment by ghost** [comment]
`tsc -d`

**Comment by extremeheat** [comment]
Feel free to open a PR to fix the problems. No 2 is not a documented API, it's an internal method, we should remove that.

**Comment by extremeheat** [comment]
Ah, I see that client.getUserData() is used inside the server player example. This should be added to the doc

**Comment by hvlxh** [comment]
also client.profile is undefined, it has xuid, uuid and another one. i
 would open a pr when i have an free time

**Comment by hvlxh** [comment]
@extremeheat fixed in pr #391,
you can mention pr and close this issue
