### ISSUE TITLE
add_player packet issue 

### ISSUE THREAD

**Issue by Pete9xi** [mhsjlw/pocket-minecraft-protocol#381]
Hi i have client connected to the server that is looking for the add_player packet when this is ran locally on a test bds server the client can receive the packet and extract the data required. but when the client is connected to the production server it never receives the add_player packet. Have you seen this before?

**Comment by ghost** [comment]
can u give us ur code?

**Comment by Pete9xi** [comment]
`

//Load config file.
const fs = require('fs')
const config = JSON.parse(fs.readFileSync('config.json', 'utf-8'))
const uuid = require('uuid');

// load discord.js
const { Client, GatewayIntentBits, EmbedBuilder} = require('discord.js')
const { MessageContent, GuildMessages, Guilds, } = GatewayIntentBits

let channel = config.channel
const token = config.token
let paradoxChannel = config.paradoxLogsChannel
var paradoxLogs = config.ParadoxEnabled
const correction = {
        "§r§4[§6Paradox§4]§r": "Paradox",
        "§4[§6Paradox§4]": "Paradox",
        "§r": "",
        "§6": "",
        "§4": ""
      };

//Device OS ids to be converted to more friendly names
var DeviceOS;




// create new discord client that can see what servers the bot is in, as well as the messages in those servers
const client = new Client({ intents: [Guilds, GuildMessages, MessageContent] })
client.login(token)

// load Bedrock-Protocol
const bedrock = require('bedrock-protocol');
const { resourceUsage } = require('process');

// bot options
const options = {
    host: config.ip,   // optional
    port: config.port,         // optional, default 19132
    username: config.username,   // the username you want to join as, optional if online mode
    offline: config.AuthType    // optional, default false. if true, do not login with Xbox Live. You will not be asked to sign-in if set to true.
}

// join server
const bot = bedrock.createClient(options)
bot.on('spawn', () => {
  console.log(`Bedrock bot logged in as ${bot.username}`)
})

// when discord client is ready, send login message
client.once('ready', (c) => {
  console.log(`Discord bot logged in as ${c.user.tag}`)
  channel = client.channels.cache.get(channel)
  if(paradoxLogs === true){
    paradoxChannel = client.channels.cache.get(paradoxChannel)
  }
  
  if (!channel) {
    console.log(`I could not find the channel (${config.channel})!`)
    process.exit(1)
  }
  if(!paradoxChannel){
  console.log(`I could not find the channel (${config.paradoxLogsChannel})!`)
  process.exit(1)
  }
})

client.on('messageCreate', (message) => {
    if(message.author.bot === true){
        /**This check will prevent a loop back mesasge. 
         * If the incoming message is from a bot it will ingore it.
         */
    }else{
        //We will then send a command to the server to trigger the message sent in discord.
        const cmd = `/tellraw @a {"rawtext":[{"text":"§8[§9Discord§8] §7${message.author.username}: §f${message.content}"}]}`
         bot.queue('command_request', {
            command: cmd,
            origin: {
            type: 'player',
            uuid: '',
            request_id: '',
    },
    internal: false,
          version: 52,
  })

    }
 
})
bot.on("packet", (packet) =>{
    if(packet.name ==='add_player'){
        console.log(packet);
    }
})
//Send connecting players device os to discord.
bot.on('add_player', (packet) => { // Listen for chat messages
    switch(packet.device_os){
        case "Win10":
            DeviceOS = "Windows PC";
            break;
        case "iOS":
            DeviceOS = "Apple Device";
            break;
        case "NintendoSwitch":
            DeviceOS = "Nintendo Switch";  
            break;
        case "Android":
        DeviceOS = "Android"; 
        break;
        // just send default
        default: 
        DeviceOS = packet.device_os;
        console.log("DeviceOS defaulted to packet.device_os");

    }
     
    if(config.useEmbed === true){
        const msgEmbed = new EmbedBuilder()
        
.setColor(0x00FFFF)
.setTitle('Server Name ')
.setDescription('[In Game] '+ packet.username +'Has joined the server using: ' + DeviceOS)
channel.send({ embeds: [msgEmbed] });
}else{
   channel.send(`[In Game] **${packet.username}** Has joined the server using: ${DeviceOS}`);
}
 })


//Redirect in-game messages to Discord channel
bot.on('text', (packet) => { // Listen for chat messages
    //Check to see if packet is a json_whisper
    if(packet.type === "json_whisper")
    {
        const msg = packet.message;
        var obj = JSON.parse(msg)
        if (obj.rawtext[0].text.includes("Discord")){
            //dont send the message otherwise it will loop 
            return;
    }
    //check for paradox messages now these could be sent to a diffrent channel if required.
    if(paradoxLogs === true){
        if (obj.rawtext[0].text.startsWith("§r§4[§6Paradox§4]§r")){
            var paradoxMsg = obj.rawtext[0].text
            const correctedText = autoCorrect(paradoxMsg, correction);
            if(config.useEmbed === true){
                const msgEmbed = new EmbedBuilder()
                .setColor(0x00FFFF)
                .setTitle('Server Name ')
                .setDescription('[In Game] '+ correctedText)
                paradoxChannel.send({ embeds: [msgEmbed] });
                return;
            }else{
                paradoxChannel.send(`[In Game] Paradox: ${paradoxMsg}`);
                return;
            }
            
        } 
    }
    if (obj.rawtext[0].text.startsWith("§r§4[§6Paradox§4]§r")){
        var paradoxMsg = obj.rawtext[0].text.replace("§r§4[§6Paradox§4]§r","");
        if(config.useEmbed === true){
            const msgEmbed = new EmbedBuilder()
            .setColor(0x00FFFF)
            .setTitle('Server Name ')
            .setDescription('[In Game] '+ "Paradox" +': ' + paradoxMsg)
            channel.send({ embeds: [msgEmbed] });
            return;
        }else{
            channel.send(`[In Game] Paradox: ${paradoxMsg}`);
            return;
        }
        
    } 
    //Check to see if player message is using a chat rank system. where the message maybe a json_whisper.
        const pattern = /§7(.+?): (.+)/;
        var matches = pattern.exec(obj.rawtext[0].text);
        const Playername = matches[1]
        const PlayersMessage = matches[2].replace("§r","");
        if(config.useEmbed === true){
            const msgEmbed = new EmbedBuilder()
            .setColor(0x00FFFF)
            .setTitle('Server Name ')
            .setDescription('[In Game] '+ Playername +': ' + PlayersMessage)
            channel.send({ embeds: [msgEmbed] });
            return;
        }else{
            channel.send(`[In Game] **${Playername}**: ${PlayersMessage}`)
            return;
        }


}
//Normal chat message no formatting required.
        if(packet.source_name === bot.username){
            /**If the chat system using json the source_name will be undefind 
             * if this is a normal chat packet the the user name will be in that 
             * field and if so if it is the bot we dont want to cause a loop.
            */

        }else{
            if(packet.message.includes("§e%multiplayer.player.joined")){
                return;
           }
            if(packet.message.includes("§e%multiplayer.player.left")){
                if(config.useEmbed === true){
                    var msg = packet.parameters+ " Has left the server."
                    var username="Server"
                    const msgEmbed = new EmbedBuilder()
        .setColor(0x00FFFF)
        .setTitle('Server Name ')
        .setDescription('[In Game] '+ username +': '+msg)
        channel.send({ embeds: [msgEmbed] });
        return;
           }else{
               channel.send(`[In Game] **${username}**: ${msg}`)
               return;
           } 
            }
            if(config.useEmbed === true){
                const msgEmbed = new EmbedBuilder()
    .setColor(0x00FFFF)
    .setTitle('Server Name ')
    .setDescription('[In Game] '+ packet.source_name +': '+packet.message)
    channel.send({ embeds: [msgEmbed] });
       }else{
           channel.send(`[In Game] **${packet.source_name}**: ${packet.message}`)
       }
        }
        
    

})



 function autoCorrect(text, correction) {
    const reg = new RegExp(Object.keys(correction).join("|"), "g");
    return text.replace(reg, (matched) => correction[matched]);
  }
  `

**Comment by Pete9xi** [comment]
Everything works fine on the test server and all events are sent to discord, but on the public server where the client connects to a public ip everything is sent but the add_player packet message

**Comment by Pete9xi** [comment]
even debugging in vs code the break point is never triggered if set

**Comment by extremeheat** [comment]
How are you sure this is an issue with bedrock-protocol and the packet is just not being sent by the server? This sounds like adupe of https://github.com/PrismarineJS/bedrock-protocol/issues/243

**Comment by Pete9xi** [comment]
Well odd thing is if I connect two instances to the server it will get one add_player packet and message sent back to discord and then messages are duplicated as expect so it could be an issue with the server

**Comment by extremeheat** [comment]
Can't reproduce, this could be the server intentionally not sending it that information, seems like a dupe of #243. It's not possible for packets to be dropped in transit per the stream encryption that Minecraft does.

**Comment by Pete9xi** [comment]
Hi since updating the server it is sending the packets as expected so not sure what was causing it very random will close this one off
