### ISSUE TITLE
How to add proxy socks support  like in mineflyer? 

### ISSUE THREAD

**Issue by pocketmineru** [mhsjlw/pocket-minecraft-protocol#401]
How to add proxy Socks support like in mineflyer? I'm trying to log into the servers, but many administrators block me, I just study the contents of the list of players. 

I need functionality that will assign a unique IP address for each bot. So that in case of blocking, I can log in again, while without such functionality, my dedicated server OVH banned by admins servers, and I can no longer log into the servers I need.

**Comment by extremeheat** [comment]
Dupe #204
