### ISSUE TITLE
Replit / glitch Support

### ISSUE THREAD

**Issue by duplicate2991** [mhsjlw/pocket-minecraft-protocol#405]
This package is not working in Replit Or Glitch
please fix this 

because i dont have host nither pc
please fix ♥️

**Comment by AnyBananaGAME** [comment]
It should work,  if it doesnt theres nothing that could be done on PrismarineJS end

**Comment by extremeheat** [comment]
Yes, this is not something we have control over. You need to either contact replit glitch support or use a proper hosting service.
