### ISSUE TITLE
Reconnecting on disconnect

### ISSUE THREAD

**Issue by Pete9xi** [mhsjlw/pocket-minecraft-protocol#407]
Hi im listening for the disconnect packet and when that happens it starts a timer to wait for the server to reboot, however i then can get it to re connect and the client account spawns in but the node script stops listening to packets is there a built in function to re connect?

**Comment by Pete9xi** [comment]
here is the example code but the bot spawn packet is not detected once it re connects 

const fs = require('fs')
const config = JSON.parse(fs.readFileSync('config.json', 'utf-8'))
const bedrock = require('bedrock-protocol');
process.env.DEBUG = 'minecraft-protocol'
var bot 
// bot options
let options
if(config.isRealm){
    //Handel the realm config here!
    console.log("Connecting to a realm");
    options = {
        realms: {
            realmInvite: config.realmInviteCode
            
          }
    }
}
else{
    console.log("Connecting to a server");
    options = {
        host: config.ip,
        port: config.port,
        username: config.username,   
        offline: config.AuthType 
    }
}
// join server
function connectClient(){
bot = bedrock.createClient(options)
}

connectClient();

bot.on('spawn', () => {
  console.log(`Bedrock bot logged in as ${bot.username}`)
})

bot.on('disconnect', (packet) => {
       
  console.log('Client disconnected:', bot.uuid);
    let remainingTime = 0.2 * 60; // 5 minutes in seconds

    console.log(`Waiting for ${remainingTime} seconds before reconnecting client.`);
  
    const timer = setInterval(() => {
      remainingTime--;
      console.log(`Remaining time: ${remainingTime} seconds`);
  
      if (remainingTime <= 0) {
        clearInterval(timer);
        connectClient();
        return
      }
    }, 1000); // Delay of 1 second
});






`

**Comment by extremeheat** [comment]
This is a question for the discord, as it's not an issue with bedrock protocol.

In order to reconnect, you must listen to the `close` event and create a new client instance and register event handlers on that client instance. Implementing a class abstraction to wrap your `createClient()` calls can help there.

```js
class MyBot {
  constructor(disconnectCb) {
    this.client = createClient()
    this.registerHandlers()
    this.client.on('close', disconnectCb)
  }
  registerHandlers() {
    this.client.on(...)
  }
}
function startBot() {
  let bot = new MyBot(startBot)
  //...
}
```

**Comment by Pete9xi** [comment]
i have resolved this by using a child process and having it listen for when main.js exits this happens when the client receives server disconnect from the Minecraft server it then restarts the main.js script when a time delay has passed but please do go ahead and close

**Comment by extremeheat** [comment]
Bad solution but ok if it works for your use case.
