### ISSUE TITLE
Ping higher than it should be even with batchingInterval set to 1

### ISSUE THREAD

**Issue by GameParrot** [mhsjlw/pocket-minecraft-protocol#422]
The relay ping from client to backend is higher than client connecting directly to backend even when the relay server is on the same device as the client. I have batchingInterval set to 1, so this may be caused by packet processing.

How to reproduce (noticeable way):
1. Make a relay to the hive (with batchingInterval set to 1)
2. Navigate through the menus
3. Connect directly to the hive and navigate the menus

Observed results:
Menu navigation is slower with relay.

This happens with servers other than the hive too (the other server i tested was zeqa, which uses pocketmine).

**Comment by extremeheat** [comment]
One of the consequences of using any proxy is you get a higher ping as information needs to travel farther and be processed for longer. You can expect a ~2-3x bump in ping, with the best case being the proxy running locally (most of overhead is processing) and worst case the proxy running externally (most of overhead is in transit). 

There is not enough information here currently to make this issue actionable. To fix that, please provide code that can reliably reproduce high pings, preferably something running locally where the proxy ping is >2x the ping directly connected to a vanilla server.

**Comment by GameParrot** [comment]
```
//process.env.DEBUG = 'minecraft-protocol'
const { Relay } = require('bedrock-protocol')
  const relay = new Relay({
    version: '1.20.0', // The version
    // host and port to listen for clients on */
    host: '127.0.0.1',
    port: 29132,
    batchingInterval: 1,
    raknetBackend: 'raknet-native',
    /* Where to send upstream packets to */
    destination: {
      batchingInterval: 1,
      host: '127.0.0.1', // Change this to server ip if needed (hive - dns lookup geo.hivebedrock.network, zeqa - dns lookup zeqa.net). Currently set to local server on default port.
      //logging: true,
      port: 19132
    }
  })
  relay.listen() // Tell the server to start listening.

  relay.on('connect', player => {
    console.log('New connection', player.connection.address)

    // Server is sending a message to the client.
    player.on('clientbound', ({ name, params }) => {
      //console.log(name);
    })
    // Client is sending a message to the server
    player.on('serverbound', ({ name, params }) => {
      //console.log(name);
    })
  })
```
Ping is much easier to notice on servers like hive and zeqa than vanilla server. Additionally, the server thinks the ping is ping between the relay and backend, not client and backend, when using commands like /ping on zeqa. Equivalent command exists on a lot of servers.

**Comment by extremeheat** [comment]
You aren't measuring anything in the code.

**Comment by GameParrot** [comment]
> You aren't measuring anything in the code.

I can tell ping is definitely higher even without measuring.

Best way to test would be to run the relay locally and hive it relay to the hive. Then disable screen animations in minecraft settings and navigate menus with and without the relay, while screen recording so you can see how many frames there are in between menus when clicking something in a menu. Higher ping = more frames between menus

**Comment by extremeheat** [comment]
We can't do anything if there isn't an objective metric to work with, so that would have to be measured in the code. I will take a look at the local vanilla latency, but I doubt there is anything bad in the current code.

**Comment by GameParrot** [comment]
How would i measure the ping from the relay to the client? I thing relay to client is the problem, not relay to backend server.

**Comment by extremeheat** [comment]
See my code and comment above

**Comment by GameParrot** [comment]
Can confirm ping increase with measuring (by doing client -> relay -> another relay -> backend with both relays printing the timestamp when a command_request is received). The second relay recieved the command about 30-50 ms later than the first on average, meaning that the relay increases ping by like 30-50 ms, which is more than it should when running locally. Also the range is like 20-80 ms.
Relay 1 out:
```
1687827060815
1687827063926
1687827065582
1687827066784
1687827067791
1687827068642
1687827069443
1687827070247
1687827070949
1687827071850
1687827072805
1687827073657
1687827074610
1687827075411
```

Relay 2 out:
```
1687827060843
1687827063952
1687827065605
1687827066808
1687827067815
1687827068667
1687827069474
1687827070329
1687827070981
1687827071882
1687827072834
1687827073686
1687827074642
1687827075444
```

**Comment by GameParrot** [comment]
Ping test: https://gist.github.com/GameParrot/a81e31e834f8bbc6b88c5d897e772fe9
Output I got:
```
C -> S: 28
S -> C: 41
-------
C -> S: 27
S -> C: 6
-------
C -> S: 29
S -> C: 28
-------
C -> S: 32
S -> C: 20
-------
C -> S: 34
S -> C: 11
-------
C -> S: 36
S -> C: 33
-------
C -> S: 38
S -> C: 24
-------
C -> S: 39
S -> C: 16
-------
C -> S: 41
S -> C: 38
-------
```
In milliseconds, connected with localhost (i consider this fixed if we can get it under 15 constantly when on localhost)

**Comment by GameParrot** [comment]
Closing once extremeheat/node-raknet-native#20 is merged and release is made
