### ISSUE TITLE
(Relay) Client is kicked when using the recipe book on xbox

### ISSUE THREAD

**Issue by Monster-Trapper** [mhsjlw/pocket-minecraft-protocol#423]
When using relay and connecting to any server (That I have tried) using the recipe book disconnects the client.
This is my console output when I enable the debug mode, directly after any recipe is selected in the recipe book.
![image](https://github.com/PrismarineJS/bedrock-protocol/assets/137791538/ccb0cc7f-7463-436f-943a-ef6fe75bb3ae)
The code I have used is directly copied from [API.md](https://github.com/PrismarineJS/bedrock-protocol/blob/master/docs/API.md#proxy-docs) except the version is set to 1.20.0  and `process.env.DEBUG = 'minecraft-protocol'` has been added to the top of the code.

**Comment by extremeheat** [comment]
Can you explain how to replicate the issue and if it happens when you join or do something in-game? If you set `logging: true` option in the Relay options you'll get more packet debugging information, please provide the console output with that set. Also to confirm, you can't replicate this in-game, right?

**Comment by Monster-Trapper** [comment]
Apologies, it has only now occurred to me that this only seems to happen only when joining a Relay server from an Xbox device so this issue may not be as striking as first thoughts might suggest.
When I added `logging: true` to the Relay options I was unable to join the world fully because of the constant stream of text being printed in my console.
To replicate this issue, I simply opened my inventory or a crafting table (presumably anything with a recipe book, such as a stonecutter, although I have not tested all available interactable blocks. [Edit: Works fine with a stonecutter]) and clicked on any available item to craft.
![image](https://github.com/PrismarineJS/bedrock-protocol/assets/137791538/2d4a9b8d-d432-469f-8ea6-ece25c1cd52d)
(Clicking/Pressing `A` here would kick the client)
I cannot replicate this issue in a normal/vanilla session of the game.

**Comment by extremeheat** [comment]
Is this still an issue on latest?

**Comment by Monster-Trapper** [comment]
Yes.

**Comment by Monster-Trapper** [comment]
This is no longer an issue as of latest.
