### ISSUE TITLE
RaknetBacked tyring to use jsp-raknet 

### ISSUE THREAD

**Issue by Pete9xi** [mhsjlw/pocket-minecraft-protocol#439]
Hi i have a server that is hosted in the cloud it has no access to root so installing cmake is not possible, im trying to tell the bedrock-protocol to use jsp-raknet as i can install the package via npm but its still trying to use raknet-native im i doing something wrong 

`   options = {
        host: config.ip,
        port: config.port,
        username: config.username,
        offline: config.AuthType,
        raknetBackend: "jsp-raknet",
    };`

**Comment by extremeheat** [comment]
`jsp-raket` does not fully work at the moment, please use `raknet-native` or `raknet-node` instead

**Comment by Pete9xi** [comment]
Would raknet-node compile the bindings without the need for build tools as root access is not possible?

**Comment by extremeheat** [comment]
There should be prebuilds provided, yes. If not you should open an issue in their repo.
