### ISSUE TITLE
What can i do with it!?!

### ISSUE THREAD

**Issue by Lorenzo2282953** [mhsjlw/pocket-minecraft-protocol#445]
I cant do anything with it, i can only make it send message and? Nothing? Please help me
Please make that the bot can send a command only if it has operator permission please

**Comment by extremeheat** [comment]
Please post on the discord (link in readme badge) for questions about usage, this issue board is for issues with the repository. The usage for the library is explained in the readme, the API doc, examples and executing other high level actions is explained in https://github.com/PrismarineJS/bedrock-protocol/wiki/Using-bedrock-protocol#so-how-do-you-do-anything-
