### ISSUE TITLE
Join and talk

### ISSUE THREAD

**Issue by Aglomation** [mhsjlw/pocket-minecraft-protocol#478]
is it possible to join with the bot and actually talk in game, kinda like mineflayer but bedrock or is this only for server hosting

**Comment by THEBOSS9345** [comment]
what you mean by talk you can chat

**Comment by Monster-Trapper** [comment]
Is this more suited for [discussions](https://github.com/PrismarineJS/bedrock-protocol/discussions)?

**Comment by extremeheat** [comment]
> is it possible to join with the bot and actually talk in game

Yes, see the README
