### ISSUE TITLE
Unsupported version 1.20.61

### ISSUE THREAD

**Issue by THEBOSS9345** [mhsjlw/pocket-minecraft-protocol#482]
![Screenshot 2024-02-09 225949](https://github.com/PrismarineJS/bedrock-protocol/assets/125090249/7dcf7cbb-aff6-47c8-ba7e-0b45283f14c8)
 wen  it shows here https://www.npmjs.com/package/bedrock-protocol it works in 1.20.61 and yes i have update the package

**Comment by extremeheat** [comment]
To update bedrock-protocol (or any Node.js package) and its dependencies after a previous install, you must run `npm update --depth 9999`

**Comment by THEBOSS9345** [comment]
i have done but i got the same error

**Comment by THEBOSS9345** [comment]
nvm i fixed it was something i have done in  the bedrock protocol while i was re making something i fixed it and it worked sorry about that

**Comment by THEBOSS9345** [comment]
thx for trying to help

**Comment by THEBOSS9345** [comment]
thx
