### ISSUE TITLE
Bedrock Protocol Not Working On Computer! What Could be the issue?

### ISSUE THREAD

**Issue by Daystormer** [mhsjlw/pocket-minecraft-protocol#491]
I am trying to connect my Minecraft server to my discord through ThirdEye so I have logs but turns out my computer is giving me issues and I do not understand what is happening. Pete the owner of ThirdEye Instructed me to contact you or I re-install windows. What could be the issue? I do not know why the bedrock protocol is not working for me

here is the command prompt that is running into issues. I have Visual Studios, Cmake, and I followed the proper instructions over on this page https://github.com/pete9xi/thirdeye

Hopefully, you can help me with this issue the command prompt text is located here: 
[message (1).txt](https://github.com/PrismarineJS/bedrock-protocol/files/14695055/message.1.txt)

Thank you,
Daystormer

**Comment by extremeheat** [comment]
Can you set the `DEBUG` environment variable on your system to `raknet`, reload the terminal and try the install again?

**Comment by extremeheat** [comment]
No update provided, reopen if you have more information
