### ISSUE TITLE
i cant send messages by joining realm

### ISSUE THREAD

**Issue by Lore228295** [mhsjlw/pocket-minecraft-protocol#496]
the this is: why do you guys add realm function if you cant do anything, like sending messages moving

the only thing you can do is: joining and nothing else.

and why you guys didnt add movements.. placing blocks...?? i dont get it

**Comment by extremeheat** [comment]
Please use the Discord for support questions, the issues board is for issues with the project and related code.

PrisamrineJS/bedrock-protocol is the Bedrock Edition analog library for [minecraft-protocol](https://github.com/PrismarineJS/node-minecraft-protocol/) that supports Java Edition. It is for people to design and build client and server software on top of. You need to be experienced the Minecraft network protocols to use it, and reverse engineer the correct packets to send and how to send them as there is no documentation.

High level functionality like provided in mineflayer (which doesn't currently support bedrock edition) is outside the intended project scope.
