### ISSUE TITLE
Support for 1.21.20

### ISSUE THREAD

**Issue by MohamadOday** [mhsjlw/pocket-minecraft-protocol#521]
Tried to just manually add the version to the module but of course, It didn't work

**Comment by Pete9xi** [comment]
It will happen at some point, based on thr github commits in the discord server they have issues with minecraft-data which bedrock-protocol needs, aleast thats what i can see, even if one was to take it upon him self to update it they still need to approve a release so you may as well wait, in the past its been a few weeks till we get a release for the current version so sit tight and just wait

**Comment by MohamadOday** [comment]
Well That is unfortunate 😞
