### ISSUE TITLE
Unknown parametrizable type: bitflags

### ISSUE THREAD

**Issue by Floatingjacob** [mhsjlw/pocket-minecraft-protocol#559]
Whenever i run the bot it just crashes and says "Unknown parametrizable type: bitflags".

here is my code
'
const bedrock = require('bedrock-protocol');
const nodemailer = require('nodemailer');

// Set up the email transporter (use correct email and password)
const transporter = nodemailer.createTransport({
  service: 'email',
  auth: {
    user: 'blablabla@email.com',  // Your email address
    pass: 'EmailPasswordBlaBlaBla'            // Your email password (consider using app-specific passwords for security)
  }
});

// Function to send email notifications when a player joins
function sendEmail(playerName) {
  const mailOptions = {
    from: 'blablabla@email.com',     // Your email address
    to: 'blablablabla@email.com',       // Email to receive the notifications
    subject: 'Minecraft Player Joined',
    text: `Player ${playerName} has joined the server.`
  };

  transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      console.log('Error sending email:', error);
    } else {
      console.log('Email sent: ' + info.response);
    }
  });
}

// Initialize client inside try-catch to handle initialization errors
let client;

function startBot() {
  try {
    client = bedrock.createClient({
      host: 'netslacking.net',  // Replace with your server IP
      port: 19132,                  // Minecraft Bedrock Edition default port
      username: 'emailbot',              // Set bot's username
    });

    // Handle player join events
    client.on('playerJoin', (player) => {
      console.log(`${player.name} has joined the game.`);
      sendEmail(player.name);  // Send email notification
    });

    // Handle protocol errors and suppress the bitflags error
    client.on('error', (err) => {
      if (err.message && err.message.includes('bitflags')) {
        console.log('Ignoring bitflags error:', err.message);
        // Attempt to reconnect if a protocol error occurs
        client.end();  // Close the connection
        startBot();    // Reinitialize the bot to reconnect
      } else {
        console.error('Error with the bot:', err);
      }
    });

    client.on('end', () => {
      console.log('Bot has disconnected from the server.');
      // Optional: Try reconnecting after disconnection
      setTimeout(() => {
        console.log('Attempting to reconnect...');
        startBot();  // Reinitialize and reconnect
      }, 5000);  // Delay before reconnecting (5 seconds)
    });

  } catch (err) {
    console.error('Failed to initialize the bot:', err);
    // Handle the error without crashing the entire bot
    setTimeout(() => {
      console.log('Attempting to start bot again...');
      startBot();  // Attempt to reinitialize the bot after an error
    }, 5000);  // Delay before retrying (5 seconds)
  }
}

// Start the bot for the first time
startBot();

// Global error handling for uncaught exceptions
process.on('uncaughtException', (err) => {
  console.error('Uncaught exception occurred, but continuing:', err);
  // Optionally log this error to a file for later review
});
'

any help would be appriceated.

**Comment by extremeheat** [comment]
You need to update your dependencies with `npm update`
